name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-bugbear flake8-black
      - name: Flake8 Lint
        run: |
          flake8 --ignore F401 --exclude __init__.py,__pycache__ --max-line-length 100 src || true
        id: flake8
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: flake8-lint-results
          path: |
            src/
            *.py
        if: always()
